### ISSUE TITLE
文字勘误

### ISSUE THREAD

**Issue by baocaixue** [wangzhiwubigdata/God-Of-BigData#22]
![image](https://user-images.githubusercontent.com/30517451/106705311-acdfb880-6628-11eb-8044-521ffa522f7e.png)
[分布式系统的基本概念](https://github.com/wangzhiwubigdata/God-Of-BigData/blob/master/%E5%88%86%E5%B8%83%E5%BC%8F%E7%90%86%E8%AE%BA/%E5%88%86%E5%B8%83%E5%BC%8F%E7%B3%BB%E7%BB%9F%E7%9A%84%E4%B8%80%E4%BA%9B%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5.md)负载均衡段落中，“bug和系统A的集群有两点不同”应该是"but"吧

**Comment by wangzhiwubigdata** [comment]
可以给我提一个pull request

**Comment by baocaixue** [comment]
close #28
