### ISSUE TITLE
16-Flink-Redis-Sink.md 文件中出现笔误

### ISSUE THREAD

**Issue by ChenShuai1981** [wangzhiwubigdata/God-Of-BigData#3]
//实例化FlinkJedisPoolConfig 配置redis
FlinkJedisPoolConfig conf = new FlinkJedisPoolConfig.Builder().setHost("127.0.0.1").**setHost**("6379").build();

此处应该为 
//实例化FlinkJedisPoolConfig 配置redis
FlinkJedisPoolConfig conf = new FlinkJedisPoolConfig.Builder().setHost("127.0.0.1").**setPort**(6379).build();

**Comment by wangzhiwubigdata** [comment]
谢谢，已改正。
