### ISSUE TITLE
你这是复制的别人的仓库吧？

### ISSUE THREAD

**Issue by ThounderStruck** [wangzhiwubigdata/God-Of-BigData#36]
你这不是原创，是复制的别人的仓库吧（https://github.com/heibaiying/BigData-Notes）？没注明出处，有点不道德

**Comment by 17809162409** [comment]
I am sorry. 我是你的粉丝。马上注明一下你原创的链接，如果给你造成困扰，我很抱歉。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月26日(周六) 晚上11:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wangzhiwubigdata/God-Of-BigData] 你这是复制的别人的仓库吧？ (#36)




 
你这不是原创，是复制的别人的仓库吧（https://github.com/heibaiying/BigData-Notes）？没注明出处，有点不道德

**Comment by Dmenghuancheng** [comment]
我看看，不太会用这个



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月28日(周一) 下午3:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [wangzhiwubigdata/God-Of-BigData] 你这是复制的别人的仓库吧？ (#36)




 I am sorry. 我是你的粉丝。马上注明一下你原创的链接，如果给你造成困扰，我很抱歉。 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年6月26日(周六) 晚上11:47 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [wangzhiwubigdata/God-Of-BigData] 你这是复制的别人的仓库吧？ (#36) 
 
 
 
 
   
 你这不是原创，是复制的别人的仓库吧（https://github.com/heibaiying/BigData-Notes）？没注明出处，有点不道德
